spring.application.name=SSAFYHome

spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.datasource.url=jdbc:mysql://192.168.204.105:3306/ssafyhome?serverTimezone=UTC
spring.datasource.username=ssafy
spring.datasource.password=ssafy

spring.jpa.show-sql=true
spring.jpa.hibernate.ddl-auto=update
spring.jpa.database-platform=org.hibernate.dialect.MySQL8Dialect

logging.level.org.hibernate.SQL=DEBUG
logging.level.org.hibernate.type.descriptor.sql=TRACE

spring.data.redis.host=localhost
spring.data.redis.port=6379

api.key_sgis_service_id=c661120d3532438fa1fb
api.key_sgis_security=e7bd4df9cef74289a778
api.key_vworld=2132B72A-8939-3003-9E7E-A44C8F075ED1
api.key.data_co_kr=GFkjjgZpoNPGpFRiONb1dG7BbqSSFJokGDONsea8gW+z2Hlj7gG4pEvsQo5sbKE4RSnCBd6ywMjmyR8sAjuJIQ==

server.tomcat.uri-encoding=UTF-8
spring.http.encoding.enabled=true
spring.http.encoding.charset=UTF-8
spring.http.encoding.force=true
